config/routes.rb
Rails.application.routes.draw do
  
  resources :participations do
    member do
      get :activate
    end
  end
  
  resources :streams do
    resources :participations
  end
  
  resources :orderquants
  
  resources :orders do
    member do
      get :activate
    end
  end
  
  resources :donations do
    member do
      put :advance
    end
  end
  
  resources :answers
  
  resources :questions do
    resources :answers
  end
  
  resources :rewards do
    resources :donations
  end
  
  resources :fundings do
    resources :questions
    resources :rewards
    resources :donations do
      member do
        put :new
      end
    end
    
    member do
      put :publish
    end
  end
  
  controller :statistics do
    get 'statistics/index' => :index
    get 'statistics/current_requests' => :current_requests
  end
  
  resources :prefs do
    collection do
      get :overview
    end
    
    member do
      put :switch
    end
  end
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  namespace :admin do
    resources :accounts
    
    resources :payments
  end
  
  resources :messages
  
  resources :memberships do
    member do
      put :accept
      get :activate
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/models/membership.rb
class Membership < ApplicationRecord
  include Tokenize
  after_initialize :fill_in_token
  
  # --- RELATIONS ------------------------------
  
  belongs_to :contact
  accepts_nested_attributes_for :contact
  
  has_many :payments, -> { order 'paid_at DESC' }, dependent: :nullify
  
  # --- VALIDATIONS ----------------------------
  
  validates_uniqueness_of :token,
        on: :create
  validates_presence_of :token, :birth_on,
      :street, :housenr, :plz, :city,
      :other_memberships, :fee_amount,
      :fee_period, :fee_mode, :recommendation, :phone_nr
  validates_presence_of :account_owner, :iban,
      if: Proc.new { |m| m.fee_mode == 'direct_debit' }
  validates_acceptance_of :accepts_debit,
      if: Proc.new { |m| m.fee_mode == 'direct_debit' }
  validates_acceptance_of :accepts_rules,
      :wants_membership
  
  # --- SCOPES ---------------------------------
  
  scope :unconfirmed, -> {
      references( :contact ).
      includes( :contact ).
      where( "contacts.status IN ( 'new', 'member' )" ) }
  scope :applications, -> {
      where status: 'new' }
  scope :accepted, -> {
      where status: 'accepted' }
  scope :member, -> {
      where status: 'member' }
  scope :want_newsletter, -> {
      references( :contact ).
      includes( :contact ).
      where( "contacts.wants_news = true" ) }
  scope :need_fee_check, -> {
      where( 'fee_check_at < ?', Time.zone.now ) }
  
  # --- INSTANCE METHODS -----------------------
  
  def to_param
    token
  end
  
  def status_text
    return 'discharged' if discharged?
    return status
  end
  
  def street_nr_text
    [ street, housenr ].compact.join ' '
  end
  
  def plz_city_text
    [ plz, city ].compact.join ' '
  end
  
  def secret
    id_hash [ token, contact_id.to_s, birth_on.to_s, plz ].join
  end
  
  # --- PREDICATES -----------------------------
  
  def application?
    status == 'new'
  end
  
  def accepted?
    status == 'accepted' and !discharged?
  end
  
  def member?
    status == 'member' and !discharged?
  end
  
  def discharged?
    ends_at and ends_at < Time.zone.now
  end
  
  def direct_debit?
    fee_mode == 'direct_debit'
  end
  
  def show_to?( in_status = 'public' )
    in_status == 'admin'
  end
  
  # --- ACTIONS --------------------------------
  
  def paid_until_at
    
  end
  
  def advance_fee_check
    logger.debug "> advance_fee_check @ membership"
    last_payment = payments.first
    paid_for_months = ( last_payment.amount / ( fee_amount / fee_period ) )
    logger.debug "-- paid_for_months: #{paid_for_months}"
    first_of_month_at = Time.zone.now.at_beginning_of_month
    self.update_attribute :fee_check_at, first_of_month_at + ( paid_for_months * 30 ).days + 5.days + rand( 300 ).minutes
  end
  
  def send_fee_request
    logger.debug "> send_fee_request @ membership"
    self.update_attribute :fee_check_at, Time.zone.now + FEE_REMINDER_PERIOD + rand( 300 ).minutes
    MembershipsMailer.
        with( membership: self ).
        payment_request.
        deliver_later
  end
  
  # --- CLASS METHODS --------------------------
  
  def self.t_period_select
    PERIOD_OPTIONS.collect { |o| [ self.human_attribute_name( "fee_period.#{o}" ), o ] }
  end
  
  def self.t_gender_select
    GENDER_OPTIONS.collect { |o| [ self.human_attribute_name( "gender.#{o}" ), o ] }
  end
  
  def self.t_mode_select
    MODE_OPTIONS.collect { |o| [ self.human_attribute_name( "fee_mode.#{o}" ), o ] }
  end
  
  def self.generate_funding
    self.where( status: [ :member, :published ] ).inject( 0 ) { |sum, m|
        sum + m.fee_amount.to_f / m.fee_period.to_f }
  end
  
  def self.potential_funding
    self.all.inject( 0 ) { |sum, m|
        sum + m.fee_amount.to_f / m.fee_period.to_f }
  end
  
  # --- CONSTANTS ------------------------------
  
  GENDER_OPTIONS = [
    'female',
    'male',
    'diverse'
  ]
  
  PERIOD_OPTIONS = [
    1,
    3,
    6,
    12
  ]
  
  MODE_OPTIONS = [
    'transferral',
    'paypal',
    'direct_debit'
  ]
  
  FEE_REMINDER_PERIOD = 8.days
  
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :require_admin, except: [ :activate, :new, :create ]
  skip_before_action :require_team, only: [ :activate, :new, :create ]
  
  before_action :check_enabled
  before_action :set_membership, only: [ :accept, :activate, :show, :edit, :update, :destroy ]
  
  # --- CUSTOM METHODS -------------------------
  
  # GET /memberships/1/accept
  def accept
    @membership.status = 'accepted'
    @membership.starts_at = Time.zone.now
    
    if @membership.save
      MembershipsMailer.with( membership: @membership ).
            membership_accepted.
            deliver_later
      render :show
      
    else
      redirect_to edit_membership_path( @membership ), notice: 'Du musst den Antrag erst korrekt ausfüllen und speichern'
    end
  end
  
  # GET /memberships/1/activate
  def activate
    @successful = false
    
    if @membership.secret == params[ :ring ]
      @membership.status = 'member'
      @membership.contact.status = 'confirmed'
      @membership.starts_at = Time.zone.now
      
      @successful = @membership.contact.save and @membership.save
    end
  end
  
  # --- STANDARD CRUD METHODS ------------------
  
  # GET /memberships
  # GET /memberships.json
  def index
    letter_selected = params[ :letter ]
    @letters = Membership.find_by_sql "
        select left( c.last_name, 1 ) as letter
          from memberships as m
            left join contacts as c
            on m.contact_id = c.id
          group by letter
          order by letter asc"
    
    @dates_list = params[ :letter ].to_s.length > 1
    case params[ :letter ]
      when 'unconfirmed'
        @memberships = Membership.unconfirmed.
            order :starts_at
      when 'new'
        @memberships = Membership.applications.
            order :starts_at
      when 'accepted'
        @memberships = Membership.accepted.
            order :starts_at
      when 'member'
        @memberships = Membership.member.
            order 'starts_at DESC'
      else
        @memberships = Membership.find_by_sql [ "
            select m.*
              from memberships as m
                left join contacts as c
                on m.contact_id = c.id
              where left( c.last_name, 1 ) = ?
              order by c.last_name", letter_selected ]
    end
  end
  
  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end
  
  # GET /memberships/new
  def new
    contact = Contact.new
    contact = current_account.contact if current_account
    @membership = Membership.new( contact: contact )
  end
  
  # GET /memberships/1/edit
  def edit
  end
  
  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new( membership_params )
    @membership.status = 'new'
    
    if current_account
      @membership.contact = current_account.contact
    else
      @membership.contact.status = 'membership'
      @membership.contact.wants_news = true
    end
    
    @membership.starts_at = Time.zone.now if @membership.starts_at.blank?
    
    respond_to do |format|
      if @membership.save
        session[ :membership_token ] = @membership.token
        
        format.html { render :create }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update( membership_params )
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    # save exit date for once and log
    @membership.update_attribute :ends_at, Time.zone.now
    write_log( 'destroy membership', @membership.to_yaml, @membership )
    
    @contact = @membership.contact
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to @contact, notice: 'Mitgliedschaft wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end
  
private
  
  # Use callbacks to share common setup or constraints between actions.
  def check_enabled
    render :not_enabled and return unless h_app_feature? :allow_membership
  end
  
  def set_membership
    @membership = Membership.find_by token: params[ :id ]
    render_404 and return if @membership.blank?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def membership_params
    params.require( :membership ).permit( :gender, :birth_on, :street, :housenr, :plz, :city, :other_memberships, :fee_amount, :fee_period, :fee_mode, :account_owner, :iban, :accepts_debit, :recommendation, :phone_nr, :accepts_rules, :wants_membership, :starts_at, :ends_at, :last_payment_at, :contact_attributes => [ :email, :first_name, :last_name ] )
  end
  
end

app/helpers/memberships_helper.rb
module MembershipsHelper
  
  def h_fee_mode_class
    @membership.fee_mode != 'direct_debit' ? 'initially_hidden' : nil
  end
  
end

app/views/memberships/_form.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: @membership.errors.count )
      %ul
        - @membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  .field
    = f.label :gender
    = f.select :gender, Membership.t_gender_select
  
  .field
    = f.label :birth_on
    = f.date_select :birth_on, start_year: 1935, end_year: ( Time.zone.now - 12.years ).year
  
  %fieldset
    %legend Adresse
    
    .field
      = f.label :street
      = f.text_field :street
    
    .field
      = f.label :housenr
      = f.text_field :housenr
    
    .field
      = f.label :plz
      = f.text_field :plz
    
    .field
      = f.label :city
      = f.text_field :city
    
  
  %fieldset
    %legend Mitgliedsbeitrag
    
    .field
      = f.label :fee_amount
      = f.text_field :fee_amount
    
    .field
      = f.label :fee_period
      = f.select :fee_period, Membership.t_period_select
    
    .field
      = f.label :fee_mode
      = f.select :fee_mode, Membership.t_mode_select, {}, data: { sel: '#fee_mode_sepa' }
    
    #fee_mode_sepa{ class: h_fee_mode_class, data: { action: 'select_shows', which: '#membership_fee_mode', values: 'direct_debit' } }
      .field
        = f.label :account_owner
        = f.text_field :account_owner
      
      .field
        = f.label :iban
        = f.text_field :iban
      
    
    .field
      = f.label :fee_check_at
      = f.date_select :fee_check_at, include_blank: true
    
  
  %fieldset
    - if @membership.member?
      %legend Mitgliedschaft
    - else
      %legend Aufnahme
    
    
    .field
      = f.label :other_memberships
      = f.text_area :other_memberships
    
    .field
      = f.label :recommendation
      = f.text_field :recommendation
    
    .field
      = f.label :phone_nr
      = f.text_field :phone_nr
    
    .field
      - if @membership.member?
        = f.label :starts_at, 'Mitglied seit'
      - elsif @membership.accepted?
        = f.label :starts_at, 'Angenommen seit'
      - else
        = f.label :starts_at, 'Antrag gestellt am'
      
      = f.date_select :starts_at
    
    .field
      = f.label :ends_at
      = f.date_select :ends_at, include_blank: true
    
  
  .actions
    = cancel_action
    = f.submit class: 'button main'
  

app/views/memberships/_form_admin.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: @membership.errors.count )
      %ul
        - @membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  .field
    = f.label :gender
    = f.select :gender, Membership.t_gender_select
  
  .field
    = f.label :birth_on
    = f.date_select :birth_on, start_year: 1935, end_year: ( Time.zone.now - 12.years ).year
  
  %fieldset
    %legend Adresse
    
    .field
      = f.label :street
      = f.text_field :street
    
    .field
      = f.label :housenr
      = f.text_field :housenr
    
    .field
      = f.label :plz
      = f.text_field :plz
    
    .field
      = f.label :city
      = f.text_field :city
    
  
  %fieldset
    %legend Mitgliedsbeitrag
    
    .field
      = f.label :fee_amount
      = f.text_field :fee_amount
    
    .field
      = f.label :fee_period
      = f.select :fee_period, Membership.t_period_select
    
    .field
      = f.label :fee_mode
      = f.select :fee_mode, Membership.t_mode_select, {}, data: { sel: '#fee_mode_sepa' }
    
    #fee_mode_sepa{ class: h_fee_mode_class, data: { action: 'select_shows', which: '#membership_fee_mode', values: 'direct_debit' } }
      .field
        = f.label :account_owner
        = f.text_field :account_owner
      
      .field
        = f.label :iban
        = f.text_field :iban
      
    
    .field
      = f.label :fee_check_at
      = f.date_select :fee_check_at, include_blank: true
    
  
  %fieldset
    - if @membership.member?
      %legend Mitgliedschaft
    - else
      %legend Aufnahme
    
    
    .field
      = f.label :other_memberships
      = f.text_area :other_memberships
    
    .field
      = f.label :recommendation
      = f.text_field :recommendation
    
    .field
      = f.label :phone_nr
      = f.text_field :phone_nr
    
    .field
      - if @membership.member?
        = f.label :starts_at, 'Mitglied seit'
      - elsif @membership.accepted?
        = f.label :starts_at, 'Angenommen seit'
      - else
        = f.label :starts_at, 'Antrag gestellt am'
      
      = f.date_select :starts_at
    
    .field
      = f.label :ends_at
      = f.date_select :ends_at, include_blank: true
    
  
  .actions
    = f.submit class: 'button main'
  

app/views/memberships/_form_new_external.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: @membership.errors.count )
      %ul
        - @membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  = render 'contacts/subform_membership', form: f, contact: @membership.contact
  
  .field
    = f.label :gender
    = f.select :gender, Membership.t_gender_select
    .help Welchem Geschlecht würdest Du Dich zuordnen?
  
  .field
    = f.label :birth_on
    = f.date_select :birth_on, start_year: 1930, end_year: ( Time.zone.now - 12.years ).year, include_blank: true
  
  %fieldset
    %legend Adresse
    .field
      .help Wir brauchen Deine Adresse, um dich postalisch anschreiben zu können.
    
    .field
      = f.label :street
      = f.text_field :street
    
    .field
      = f.label :housenr
      = f.text_field :housenr
    
    .field
      = f.label :plz
      = f.text_field :plz
    
    .field
      = f.label :city
      = f.text_field :city
    
  
  .field
    = f.label :other_memberships
    = f.text_area :other_memberships
    .help Bei welchen anderen Organisationen warst du oder bist du Mitglied?
  
  %fieldset
    %legend Mitgliedsbeitrag
    
    .help
      Die
      = h_orga_name
      erhebt Mitgliedsbeiträge in freiwilliger Höhe. Ziel ist ein Beitrag von 0,5% des jeweiligen Einkommens. Es bestimmt jedoch jedes Mitglied selbst, ob er/sie sich danach richten möchte.
      = link_to 'Mehr Infos'.html_safe, '#', data: { action: 'show_hide', sel: '#fee_help' }
    
    .help#fee_help.initially_hidden
      Die Beiträge werden im Voraus je Zahlungszeitraum erhoben. Beitragshöhe, Zahlungsweise und Zahlungsfrequenz lassen sich zu jedem Zahlungszeitraumsanfang auf Antrag ändern.
    
    .field
      = f.label :fee_amount
      = f.text_field :fee_amount
    
    .field
      = f.label :fee_period
      = f.select :fee_period, Membership.t_period_select
    
    .field
      = f.label :fee_mode
      = f.select :fee_mode, Membership.t_mode_select, {}, data: { sel: '#fee_mode_sepa' }
    
    #fee_mode_sepa{ class: h_fee_mode_class, data: { action: 'select_shows', which: '#membership_fee_mode', values: 'direct_debit' } }
      .field
        = f.label :account_owner
        = f.text_field :account_owner
      
      .field
        = f.label :iban
        = f.text_field :iban
      
      .field
        = f.check_box :accepts_debit
        = f.label :accepts_debit do
          Ich ermächtige
          = h_orga_name
          hiermit, den Mitgliedsbeitrag von meinem Konto mittels Lastschrift einzuziehen.
          = link_to 'Mehr Infos'.html_safe, '#', data: { action: 'show_hide', sel: '#sepa_help' }
        .help#sepa_help.initially_hidden
          Der Mitgliedsbeitrag wird regelmäßig mittels SEPA-Lastschrift von meinem Konto eingezogen. Ich kann innerhalb von acht Wochen, beginnend mit dem Belastungsdatum, die Erstattung des belasteten Betrages verlangen. Es gelten dabei die mit meinem Kreditinstitut vereinbarten Bedingungen. Das Mandat gilt für eine wiederkehrende Zahlung. Die Mandatsreferenz wird separat mitgeteilt.
          Gläubiger-Identifikationsnummer IBAN (Organisation, Adresse)
        
      
    
  
  %fieldset
    %legend Aufnahme
    
    .field
      = f.label :recommendation
      = f.text_field :recommendation
      .help
        Mit welchen Menschen aus der
        = h_orga_name
        hattest du bisher Kontakt und eventuell worüber.
      
    
    .field
      = f.label :phone_nr
      = f.text_field :phone_nr
      .help Wir würden uns gerne bei dir vorstellen und mit dir über deine Beweggründe und Ziele sprechen. Vielleicht hast du auch Anregungen für uns.
    
    .field
      = f.check_box :accepts_rules
      = f.label :accepts_rules do
        Hiermit stimme ich dem
        = link_to 'Grundkonsens von ' + h_orga_name, '/grundkonsens'
        zu und richte mein, die Organisation betreffendes, Handeln nach diesem aus.
      
    
    .field
      = f.check_box :wants_membership
      = f.label :wants_membership do
        Hiermit werde ich Mitglied von
        = h_orga_name + '.'
        Ich bin damit einverstanden, dass meine personenbezogenen Daten unter Beachtung der DSGVO (Verordnung EU 2016/679) gespeichert und innerhalb der Organisation verarbeitet werden. Eine Weitergabe an Dritte zu anderen Zwecken wird ausgeschlossen. Ich stimme zu, dass mein Vorname, Nachname, Wohnort sowie die angegebene E-Mail-Adresse intern an Mitglieder zum Aufbauen von Ortsgruppen weitergegeben wird. Als Mitglied erhalte ich automatisch den Newsletter der Organisation. Eine Abmeldung davon ist jederzeit möglich.
      
    
  
  .actions
    = f.submit "Mitgliedschaft beantragen", class: 'button main'
  

app/views/memberships/_preview.html.haml
= link_to membership, class: 'membership_preview' do
  .label
    .name= membership.contact.name_text
    .email= membership.contact.email
  
  = render 'general/badge_cell', contact: membership.contact
  
  .angle= image_tag 'sym/angle_right_s25.svg'

app/views/memberships/index.html.haml
%h1 Alle Mitgliedschaften

- if false
  %p
    = link_to new_membership_path, class: 'button' do
      = image_tag 'sym/plus_w100.svg', size: '20x20'
      Neu
    
  

%ul.letters_list
  %li= link_to 'all', memberships_path
  
  - @letters.each do |letter|
    %li= link_to letter.letter.capitalize, memberships_path( letter: letter.letter )
  

- if @memberships.blank?
  .list_title
    = pluralize Membership.count, 'Mitglieder / Anträge'
    &nbsp;&nbsp;
    = link_to image_tag( 'sym/envelope_w100.svg' ), new_message_path( to: 'members' ), remote: true, class: 'sym_button'
  
  .remote_form.initially_hidden#new_message
  
  %ul.info_list
    %li
      davon
      %strong= link_to Membership.unconfirmed.count, memberships_path( letter: 'unconfirmed' )
      unbestätigt
    
    %li
      davon
      %strong= link_to Membership.applications.count, memberships_path( letter: 'new' )
      neue Anträge
    
    %li
      davon
      %strong= link_to Membership.accepted.count, memberships_path( letter: 'accepted' )
      angenommen
    
    %li
      davon
      %strong= link_to Membership.member.count, memberships_path( letter: 'member' )
      Mitglieder
    
    %li
      = Membership.want_newsletter.count
      wollen Newsletter
    
    %li= "bringen Budget von #{number_to_currency( Membership.generate_funding )} pro Monat"
    %li= "bringen Budget von #{number_to_currency( Membership.potential_funding )} pro Monat, wenn alle Anträge angenommen werden"
  
- else
  %ul.memberships_list
    - the_date = Time.mktime( 1970, 1, 1 )
    - @memberships.each do |membership|
      - if the_date != membership.starts_at.at_midnight and @dates_list
        - the_date = membership.starts_at.at_midnight
        %li.separator
          =l the_date, format: :short_day
        
      
    
      %li= render 'preview', membership: membership
    
  

app/views/memberships/new_admin.html.haml
%h1 Neue Mitgliedschaft

= render 'form_admin'

app/views/memberships/not_enabled.html.haml
%h1 Sorry...
%p
  Mitgliedschaften sind bei uns
  %strong im Augenblick nicht möglich.

%p
  Du kannst aber gerne unseren
  = link_to 'Newsletter abonnieren', new_contact_path
  und bekommst dann Bescheid, wenn wir Mitgliedschaften anbieten.

app/views/memberships/show.html.haml
.membership_page
  = render 'contacts/show_header', contact: @membership.contact
  
  = render 'admin/accounts/tabs', contact: @membership.contact, active_tab: 'membership'
  
  .membership_details
    .status{ class: @membership.status_text }
      = @membership.status_text
    
    %h1.membership_token
      = @membership.token
      .subtitle Mitgliedsnummer
    
    %h4 Persönliches
    %p
      Geschlecht:
      %strong= @membership.gender
      %br
      Geburtstag:
      %strong=l @membership.birth_on
    
    %h4 Adresse
    %p
      %strong= @membership.street_nr_text
      %br
      %strong= @membership.plz_city_text
    
    %h4 Mitgliedbeitrag
    %p
      Beitrag:
      %strong
        = number_to_currency @membership.fee_amount
        = Membership.human_attribute_name "fee_period.#{@membership.fee_period}"
        via
        = Membership.human_attribute_name "fee_mode.#{@membership.fee_mode}"
      
    
    - if @membership.direct_debit?
      %p
        Kontoinhaber:in:
        %strong= @membership.account_owner
        %br
        IBAN:
        %strong= @membership.iban
        
        %br
        Letzte Zahlung:
        - if @membership.fee_check_at
          %strong=l @membership.fee_check_at, format: :short_day
          
        - else
          %strong keine bisher
        
      
    
    - if @membership.member?
      %h4 Mitgliedschaft
    - else
      %h4 Aufnahme
    
    - unless @membership.other_memberships.blank?
      %p
        Andere Mitgliedschaften:
        %strong= @membership.other_memberships
      
    
    %p
      Empfehlung durch:
      %strong= @membership.recommendation
      %br
      Telefon:
      %strong= @membership.phone_nr
    
    %p
      - if @membership.member?
        Mitglied seit:
      - elsif @membership.accepted?
        Angenommen seit:
      - else
        Antrag gestellt am:
      
      %strong= l @membership.starts_at, format: :short_day
      - if @membership.ends_at
        %br
        Beendet am:
        %strong= l @membership.ends_at, format: :short_day
      
    
    .action_buttons
      - unless @membership.member? and h_is_admin?
        = link_to 'Aufnehmen', accept_membership_path( @membership ), method: :put, class: 'button', title: 'Als Mitglied aufnehmen'
    
      
      = link_to image_tag( 'sym/pencil_w100.svg' ), edit_membership_path( @membership ), class: 'sym_button', title: 'bearbeiten'
      = link_to image_tag( 'sym/bin_w100.svg' ), @membership, method: :delete, data: { confirm: "Willst Du die Mitgliedschaft für '#{@membership.contact.name_text}' wirklich löschen?\n\nDie Aktion kann nicht rückgängig gemacht werden." }, class: 'sym_button danger', title: 'Mitgliedschaft löschen'
    
  