config/routes.rb
Rails.application.routes.draw do
  
  resources :participations do
    member do
      get :activate
    end
  end
  
  resources :streams do
    resources :participations
  end
  
  resources :orderquants
  
  resources :orders do
    member do
      get :activate
    end
  end
  
  resources :donations do
    member do
      put :advance
    end
  end
  
  resources :answers
  
  resources :questions do
    resources :answers
  end
  
  resources :rewards do
    resources :donations
  end
  
  resources :fundings do
    resources :questions
    resources :rewards
    resources :donations do
      member do
        put :new
      end
    end
    
    member do
      put :publish
    end
  end
  
  controller :statistics do
    get 'statistics/index' => :index
    get 'statistics/current_requests' => :current_requests
  end
  
  resources :prefs do
    collection do
      get :overview
    end
    
    member do
      put :switch
    end
  end
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  namespace :admin do
    resources :accounts
    
    resources :payments
  end
  
  resources :messages
  
  resources :memberships do
    member do
      put :accept
      get :activate
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/models/decision.rb
class Decision < ApplicationRecord
  include Tokenize
  after_initialize :fill_in_token
  
  include Publish
  after_initialize :set_publish_status
  
  belongs_to :account
  has_many :proposals, dependent: :destroy
  
  # --- VALIDATIONS ----------------------------
  
  validates_presence_of :title
  
  # --- SCOPES ---------------------------------
  
  scope :published, -> {
        where status: 'published' }
  
  # --- PREDICATES -----------------------------
  
  def is_selection?
    variant == 'selection'
  end
  
  def preparing?
    !published?
  end
  
  def proposing?
    logger.debug "-- published?: #{published?}"
    published? and Time.zone.now <= end_proposals_at
  end
  
  def voting?
    published? and ( Time.zone.now > end_proposals_at and
        Time.zone.now <= end_voting_at )
  end
  
  def votable_by?( in_account )
    voting? and not_voted_by?( in_account )
  end
  
  def active?
    published? and ( Time.zone.now <= end_voting_at )
  end
  
  def done?
    published? and ( Time.zone.now > end_voting_at )
  end
  
  def old?
    published? and ( Time.zone.now - OLD_TIME_SPAN > ( show_results_at.blank? ? end_voting_at : show_results_at ) )
  end
  
  def show_results?
    return done? if show_results_at.blank?
    published? and ( Time.zone.now > show_results_at )
  end
  
  def not_voted_by?( in_account )
    return true if in_account.blank?
    in_account.votes.for_decision( self ).all? { |v| v.status == 'new' }
  end
  
  def voted_by?( in_account )
    return false if in_account.blank?
    votes = proposals.collect { |p| p.votes_for in_account }.flatten.uniq
    return ( votes.count > 0 and votes.all? { |v|
              v.status == 'published' } )
  end
  
  # --- INSTANCE METHODS -----------------------
  
  def to_param
    "#{token}"
  end
  
  def preview_text
    title
  end
  
  def vote_count_for( in_account )
    proposals.collect { |p|
        p.vote_for in_account }.compact.count
  end
  
  def proposal_count
    proposals.published.count
  end
  
  def voters_published
    unless defined? @_voters_published
      @_voters_published = proposals.published.collect { |p|
        p.voters_published }.flatten.uniq
    end
    return @_voters_published
  end
  
  def winning_proposals
    return nil unless proposals.any? { |p| p.has_votes? }
    if is_selection?
      proposals.
          reject { |p| p.selection_value < 1 }.
          sort_by { |p| p.selection_value }.
          reverse[ 0..(vote_count - 1) ]
    else
      proposals.
          sort_by { |p| p.votes_value }.
          first
    end
  end
  
  # --- CLASS METHODS --------------------------
  
  def self.t_variant_select
    VARIANT_OPTIONS.collect { |o| [ self.human_attribute_name( "variant.#{o}" ), o ] }
  end
  
  # --- CONSTANTS ------------------------------
  
  OLD_TIME_SPAN = 3.weeks
  
  VARIANT_OPTIONS = [
    'sk',
    'selection'
  ]
  
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :set_decision, only: [ :publish, :vote, :show, :edit, :update, :destroy ]
  skip_before_action :require_team
  before_action :require_decider
  
  # --- CUSTOM METHODS -------------------------
  
  # PUT /decisions/1/publish
  def publish
    @decision.status = 'published'
    
    respond_to do |format|
      if @decision.save
        format.html { redirect_to @decision, notice: 'Entscheidung wurde bereit gemacht.' }
        format.json { render :show, status: :published, location: @decision }
      else
        format.html { redirect_to @decision, alert: 'Entscheidung konnte bereit gemacht werden.' }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /decisions/1/vote
  def vote
    current_account.votes.for_decision( @decision ).each do |vote|
      vote.status = 'published'
      vote.save!
    end
    
    redirect_to @decision, notice: 'Deine Stimmen wurden angenommen.'
  end
  
  # --- INSTANCE METHODS -----------------------
  
  # GET /decisions
  # GET /decisions.json
  def index
    @stage = params[ :stage ] || 'voting'
    published_decisions = Decision.published.includes( proposals: [ :votes ] ).order( created_at: :desc, id: :asc ).references( :proposals )
    logger.debug "-- selected published_decisions"
    
    @own_decisions = Decision.where( account: current_account ).order created_at: :desc
    @decisions = []
    case @stage
      when 'own'
        @decisions = @own_decisions
      when 'preparation'
        @decisions = Decision.where( status: 'new' ).order created_at: :desc
      when 'proposing'
        @decisions = published_decisions.select { |d| d.proposing? }
      when 'voting'
        @decisions = published_decisions.select { |d| d.voting? }
      when 'done'
        @decisions = published_decisions.select { |d| d.done? and !d.old? }
      when 'archive'
        @decisions = published_decisions.select { |d| d.done? and d.old? }
    end
    
    write_log 'index_decisions', @stage
  end
  
  # GET /decisions/1
  # GET /decisions/1.json
  def show
    if @decision.done?
      @decision = Decision.
          where( token: params[ :id ] ).
          references( proposals: [ votes: [ :account ] ] ).
          includes( proposals: [ votes: [ :account ] ] ).first
    end
    
    write_log 'show_decisions', nil, @decision
  end
  
  # GET /decisions/new
  def new
    @decision = Decision.new variant: 'SK', vote_count: 1
    limit = ( Time.zone.now + 1.hour ).beginning_of_hour
    @decision.end_proposals_at = limit + 1.day
    @decision.end_voting_at = limit + 2.days
  end
  
  # GET /decisions/1/edit
  def edit
  end
  
  # POST /decisions
  # POST /decisions.json
  def create
    @decision = Decision.new( decision_params )
    @decision.account = current_account
    
    respond_to do |format|
      if @decision.save
        format.html { redirect_to @decision, notice: 'Decision was successfully created.' }
        format.json { render :show, status: :created, location: @decision }
      else
        format.html { render :new }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /decisions/1
  # PATCH/PUT /decisions/1.json
  def update
    respond_to do |format|
      if @decision.update(decision_params)
        format.html { redirect_to @decision, notice: 'Decision was successfully updated.' }
        format.json { render :show, status: :ok, location: @decision }
      else
        format.html { render :edit }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /decisions/1
  # DELETE /decisions/1.json
  def destroy
    @decision.destroy
    respond_to do |format|
      format.html { redirect_to decisions_url, notice: 'Decision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
private
  # Use callbacks to share common setup or constraints between actions.
  def set_decision
    @decision = Decision.find_by token: params[ :id ]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def decision_params
    params.require( :decision ).permit( :variant, :vote_count, :title, :description, :end_proposals_at, :end_voting_at )
  end
  
end

app/helpers/decisions_helper.rb
module DecisionsHelper
  
  def h_decision_editable?
    logger.debug "> h_editable? @ DecisionsHelper"
    return false if @decision.voting? or @decision.done?
    current_account and
        current_account == @decision.account
  end
  
end

app/views/decisions/_form.html.haml
= form_for @decision do |f|
  - if @decision.errors.any?
    #error_explanation
      %h2=t( 'errors.template.header', model: I18n.t( "activerecord.models.decision.one" ), count: @decision.errors.count )
      %ul
        - @decision.errors.messages.each do |message|
          %li=t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.decision.#{message.first}" )
        
      
    
  
  .field
    = f.label :variant
    = f.select :variant, Decision.t_variant_select, {}, data: { sel: '#vote_count' }
  
  .field.initially_hidden#vote_count
    = f.label :vote_count
    = f.number_field :vote_count
  
  .field
    = f.label :title
    = f.text_field :title, placeholder: 'z.B. welche Farbe soll das Logo haben?'
  
  .field
    = f.label :description
    = f.text_area :description, placeholder: 'hier eine genauere Beschreibung der Fragestellung'
  
    
  .field
    = f.label :end_proposals_at
    = f.datetime_select :end_proposals_at
  
  .field
    = f.label :end_voting_at
    = f.datetime_select :end_voting_at
  
  .actions
    = cancel_action
    = f.submit
  

app/views/decisions/_infos.html.haml
.decision_infos
  - if decision.proposing?
    bisher
  
  - if decision.proposal_count > 0
    %strong.number.proposals= decision.proposal_count
    Vorschläge
    
  - else
    keine Vorschläge...
  
  - if decision.voting? or decision.done?
    &nbsp;&nbsp;
    - unless decision.done?
      bisher
    
    - if decision.voters_published.count > 0
      %strong.number.votes= decision.voters_published.count
      Abstimmende
      
    - else
      keine Abstimmenden...
    
  
  - if decision.voted_by? current_account
    .end_aligned
      = image_tag 'sym/tick_mark.svg', class: 'icon'
      ich habe abgestimmt
    
  

app/views/decisions/_preview.html.haml
= link_to decision, class: 'preview decision_prview', id: decision.token do
  
  - if !decision.published?
    .date in Vorbereitung...
    
  - elsif decision.proposing?
    .date
      .status_badge.proposing Vorschläge
      bis
      =l decision.end_proposals_at, format: :very_short_day_time
    
  - elsif decision.voting?
    .date
      .status_badge.voting{ class: decision.voted_by?( current_account ) ? 'done' : nil } Abstimmen
      bis
      =l decision.end_voting_at, format: :very_short_day_time
    
  - else
    .date
      .status_badge.done Abgestimmt
      am
      =l decision.end_voting_at, format: :very_short_day_time
    
  
  .next_arrow
    = image_tag 'sym/angle_right_s25.svg'
  
  .title= decision.title
  .description= h_format_preview decision.description, 240
  
  = render 'infos', decision: decision

app/views/decisions/_proposals_section.html.haml
%section.proposals_section
  = render 'proposals/index', proposals: @decision.proposals
  
  .proposal_form_block
    - if @decision.preparing?
      = link_to publish_decision_path( @decision ), method: :put, class: 'proposal_button' do
        .label Diese Entscheidung jetzt
        .button= 'Bereit machen'
      
    - elsif @decision.proposing?
      = link_to new_decision_proposal_path( @decision ), remote: true, class: 'proposal_button', id: 'new_proposal_button' do
        = image_tag 'sym/plus_w100.svg', class: 'button round'
        .label Neuer Vorschlag...
      
      #new_proposal
      
    - elsif @decision.votable_by?( current_account )
      = link_to vote_decision_path( @decision ), method: :put, class: 'proposal_button', id: 'vote_button', data: { confirm: "Möchtest du diese Bewertungen der Optionen für die Abstimmung endgültig einreichen?\n\nDiese Aktion kann nicht rückgängig gemacht werden." } do
        .label Wie oben bewertet...
        .button= 'abstimmen'
      
    - elsif @decision.voting?
      .proposal_button
        .label
          Abstimmung läuft noch
          - if @decision.end_voting_at - Time.zone.now >= 1.day
            bis
            =l @decision.end_voting_at, format: :very_short_day_time
          - else
            = distance_of_time_in_words_to_now @decision.end_voting_at
        
      
    - elsif @decision.done?
      .proposal_button
        .label
          Abstimmung beendet.
          %br
          Veröffentlichung der Ergebnisse
          %br
          - if @decision.show_results_at - Time.zone.now >= 1.day
            am
            =l @decision.show_results_at, format: :very_short_day_time
          - else
            in
            = distance_of_time_in_words_to_now @decision.show_results_at
          
        
      
    
  

app/views/decisions/_result_section.html.haml
- result_proposal = decision.winning_proposals
- other_proposals = decision.proposals.reject { |p| p == result_proposal }.sort_by { |p| p.votes_value }

%section.result_section
  - if result_proposal
    %header
      Ergebnis der Abstimmung
    
    .proposal_detail
      .title
        .number
          Vorschlag
          %strong= result_proposal.position
        
        = result_proposal.title
      
      .description= h_format result_proposal.description
      .result Vorschlag mit geringstem Widerstand
      = render 'proposals/result_scale', proposal: result_proposal
      
    
  
  #proposals_list
    - if result_proposal
      %header.list_title
        Die
        = other_proposals.count
        weiteren Vorschläge
      
    
    %ul.proposals_list
      - other_proposals.each do |proposal|
        = render 'proposals/preview', proposal: proposal
      
    
  

app/views/decisions/_selection_section.html.haml
- selected_proposals = decision.winning_proposals
- other_proposals = decision.proposals.reject { |p| selected_proposals.include?( p ) }.sort_by { |p| p.selection_value }.reverse

- if selected_proposals
  %section.result_section
    #proposals_list
      .list_title Ausgewähle Vorschläge
      %ul.proposals_list.selected
        - selected_proposals.each do |proposal|
          = render 'proposals/preview', proposal: proposal
        
      
      .list_title Weitere Vorschläge
      %ul.proposals_list
        - other_proposals.each do |proposal|
          = render 'proposals/preview', proposal: proposal
        
      
    
  

app/views/decisions/_tabs.html.haml
- active_tab = 'voting' unless active_tab != nil

- # --------------------------------------------
- logger.debug "-- active_tab: #{active_tab}"
.tabs_block
  %ul.tabs_block_scroller
    - unless @own_decisions.blank?
      - if active_tab == 'own'
        %li.tab.active Meine
      - else
        %li.tab= link_to 'Meine', decisions_path( stage: 'own' )
      
    
    - if active_tab == 'preparation'
      %li.tab.active Neu
    - else
      %li.tab= link_to 'Neu', decisions_path( stage: 'preparation' )
    
    - if active_tab == 'proposing'
      %li.tab.active Vorschlag
    - else
      %li.tab= link_to 'Vorschlag', decisions_path( stage: 'proposing' )
    
    - if active_tab == 'voting'
      %li.tab.active Abstimmung
    - else
      %li.tab= link_to 'Abstimmung', decisions_path( stage: 'voting' )
    
    - if active_tab == 'done'
      %li.tab.active Fertig
    - else
      %li.tab= link_to 'Fertig', decisions_path( stage: 'done' )
    
    - if active_tab == 'archive'
      %li.tab.active Archiv
    - else
      %li.tab= link_to 'Archiv', decisions_path( stage: 'archive' )
    
  

app/views/decisions/edit.html.haml
- cancel_action = capture do
  = link_to 'Abbrechen', decisions_path, class: 'button'


%h1 Entscheidung bearbeiten
- case
- when !@decision.published?
  %p
    Solange die Entscheidung noch nicht bereit ist, kannst du beliebig ändern.
  
- when @decision.proposing?
  %p
    Solange die Vorschlagsphase läuft, kannst du die Texte noch verbessern oder die Vorschlagsphase verlängern.
  

= render 'form', cancel_action: cancel_action

app/views/decisions/index.html.haml
- h_title 'Entscheidungen'
- h_description( h_page_description_for 'decisions' )

%h1 Entscheidungen
%p
  Die Liste aller Entscheidungen, zu denen die
  - if current_account.has_membership?
    Mitglieder
  - else
    = link_to 'Mitglieder', '/mitglied_werden'
  
  der
  = h_orga_name
  Vorschläge erarbeiten und dann abstimmen.

- if h_is_user?
  %p
    = link_to 'Neue Entscheidung starten...', new_decision_path
  

= render 'tabs', active_tab: @stage

.tab_view
  - if @decisions.blank?
    %p.help_text Keine Entscheidungen in dieser Kategorie
  - else
    %ul.decisions_list
      - @decisions.each do |decision|
        %li= render 'preview', decision: decision
      
    
  

app/views/decisions/new.html.haml
- cancel_action = capture do
  = link_to 'Abbrechen', decisions_path, class: 'button'


%h1 Neue Entscheidung
%p
  Hier kannst du eine neue Entscheidung anstossen.
  %br
  Beschreibe dazu präzise, zu welcher Fragestellung, du Abstimmungsvorschläge anbieten möchtest.

= render 'form', cancel_action: cancel_action

app/views/decisions/show.html.haml
- h_page_title @decision.title
- h_description truncate( strip_tags( @decision.description ), length: 250 )

%article.decision_detail
  - unless @decision.published?
    .status= @decision.status
  
  %h1.title= @decision.title
  
  .action_buttons
    - if h_decision_editable?
      = link_to image_tag( 'sym/pencil_w100.svg' ),
            edit_decision_path( @decision ),
            class: 'sym_button', title: 'Entscheidung ändern'
      = link_to image_tag( 'sym/bin_w100.svg' ),
            @decision, method: :delete,
            class: 'sym_button', title: 'Entscheidung löschen'
    
  
  .variant
    via
    %strong= Decision.human_attribute_name( "variant.#{@decision.variant}" )
    - if @decision.is_selection?
      %br
      %strong
        = @decision.vote_count
        Stimmen
      
      - if @decision.done?
        waren
      - else
        sind
      
      zu vergeben
    
  
  .description= h_format @decision.description
  
  - if @decision.done?
    .date
      %strong
        Abgestimmt am
        =l @decision.end_voting_at, format: :very_short_day_time
      
    
  - else
    .date
      Vorschläge bis
      =l @decision.end_proposals_at, format: :very_short_day_time
    
    .date
      Abstimmen bis
      =l @decision.end_voting_at, format: :very_short_day_time
    
  
  = render 'infos', decision: @decision

- if @decision.proposing?
  %section.explanation_section
    %h3 Vorschlagsphase
    %p
      Diese Abstimmung befindet sich in der Vorschlagsphase.
      %br
      Es werden (weitere) Vorschläge gesammelt, die die Fragestellung beantworten könnten und über die später abgestimmt werden soll.
    
    %p
      Mit der Plus-Taste ganz unten können neue Vorschläge eingereicht werden.
    
  

- if @decision.show_results?
  - if @decision.is_selection?
    = render 'decisions/selection_section', decision: @decision
  - else
    = render 'decisions/result_section', decision: @decision
  
- else
  = render 'decisions/proposals_section', decision: @decision