config/routes.rb
Rails.application.routes.draw do
  
  resources :participations do
    member do
      get :activate
    end
  end
  
  resources :streams do
    resources :participations
  end
  
  resources :orderquants
  
  resources :orders do
    member do
      get :activate
    end
  end
  
  resources :donations do
    member do
      put :advance
    end
  end
  
  resources :answers
  
  resources :questions do
    resources :answers
  end
  
  resources :rewards do
    resources :donations
  end
  
  resources :fundings do
    resources :questions
    resources :rewards
    resources :donations do
      member do
        put :new
      end
    end
    
    member do
      put :publish
    end
  end
  
  controller :statistics do
    get 'statistics/index' => :index
    get 'statistics/current_requests' => :current_requests
  end
  
  resources :prefs do
    collection do
      get :overview
    end
    
    member do
      put :switch
    end
  end
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  namespace :admin do
    resources :accounts
    
    resources :payments
  end
  
  resources :messages
  
  resources :memberships do
    member do
      put :accept
      get :activate
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/models/reward.rb
class Reward < ApplicationRecord
  include Tokenize
  include Picturize
  
  after_initialize :fill_in_token
  
  belongs_to :funding, optional: true
  has_one_attached :picture
  
  has_many :donations, dependent: :nullify # TODO!!
  has_many :orderquants, dependent: :nullify # TODO!!
  
  # --- VALIDATIONS ----------------------------
  
  validates :token,
        presence: true,
        uniqueness: true
  validates_presence_of :title
  
  # --- SCOPES ---------------------------------
  
  scope :published, -> { where( status: 'published' )
        .where( 'published_at < ?', Time.zone.now ) }
  
  # --- INSTANCE METHODS -----------------------
  
  def to_param
    "#{token}-#{title.parameterize}"
  end
  
  def preview_text
    title
  end
  
  def ordered
    donations.received.size +
        orderquants.inject( 0 ) { |sum, o|
            sum + o.quantity.to_i }
  end
  
  # --- Predicates -----------------------------
  
  def has_picture?
    picture.attached?
  end
  
  # --- CONSTANTS ------------------------------
  
  STATUS_OPTIONS = [
    'new',
    'published'
  ]
  
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [ :show, :edit, :update, :destroy ]
  before_action :set_funding, only: [ :new, :create ]
  
  skip_before_action :require_team
  before_action :require_editor, except: [ :index, :show ]
  
  # --------------------------------------------
  # CRUD methods
  
  # GET /rewards
  # GET /rewards.json
  def index
    render 'pages/no_access' and return unless h_page_accessible? 'rewards', current_account
    
    if h_is_editor?
      @rewards = Reward.all
      
    else
      @rewards = Reward.published
    end
    
    write_log 'index_rewards'
  end
  
  # GET /rewards/new
  def new
    if defined? @funding
      @reward = @funding.rewards.build status: 'new'
    else
      @reward = Reward.new
    end
  end
  
  # GET /rewards/1/edit
  def edit
  end
  
  # POST /rewards
  # POST /rewards.json
  def create
    if defined? @funding
    @reward = @funding.rewards.build( reward_params  )
    else
      @reward = Reward.new( reward_params )
    end
    
    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward.funding ? @reward.funding : rewards_path, notice: 'Produkt wurde erfolgreich gespeichert.' }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update( reward_params )
        format.html { redirect_to @reward.funding ? @reward.funding : rewards_path, notice: 'Produkt wurde erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @funding = @reward.funding
    @reward.destroy
    
    respond_to do |format|
      format.html { redirect_to @funding, notice: 'Produkt wurde gelöscht.' }
      format.json { head :no_content }
    end
  end
  
private
  # Use callbacks to share common setup or constraints between actions.
  def set_reward
    @reward = Reward.find_by token: params[ :id ].split( '-' ).first
    render_404 and return if @reward.blank?
  end
  
  def set_funding
    if numeric? params[ :funding_id ]
      @funding = Funding.find params[ :funding_id ].to_i
    elsif params[ :funding_id ]
      @funding = Funding.find_by token: params[ :funding_id ].split( '-' ).first
    end
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def reward_params
    params.require( :reward ).permit( :status, :picture, :price, :title, :category, :available, :description, :delivery )
  end
  
end

app/helpers/rewards_helper.rb
module RewardsHelper
  
  def h_reward_editable?( in_reward )
    h_is_admin? or
        in_reward.funding.blank? ?
            h_is_sales? :
            ( h_is_editor? and in_reward.funding.not_started? )
  end
  
end

app/views/rewards/_availability_infos.html.haml
.ordered
  - unless reward.available.blank?
    - if reward.available <= 0
      zur Zeit nicht lieferbar
    - else
      noch
      = reward.available - reward.ordered
      vorrätig
    
  

app/views/rewards/_delivery_infos.html.haml
.delivery
  - unless reward.delivery.blank?
    = reward.delivery
  

app/views/rewards/_form.html.haml
- initially_hidden = false unless defined? initially_hidden
- cancel_action = nil unless defined? cancel_action

= form_for [ @reward.funding, @reward ] do |f|
  - if @reward.errors.any?
    #error_explanation
      %h2=t( 'errors.template.header', model: I18n.t( "activerecord.models.reward.one" ), count: @reward.errors.count )
      %ul
        - @reward.errors.messages.each do |message|
          %li=t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.reward.#{message.first}" )
        
      
    
  
  .field
    = f.label :status
    = f.select :status, Reward::STATUS_OPTIONS
  
  .field.picture
    = f.label :picture
    - if @reward.has_picture?
      = render 'general/picture_preview', entity: @reward
    
    = f.file_field :picture
  
  .field
    = f.label :price
    = f.number_field :price, step: 0.01, placeholder: 'z.B. 11,50'
  
  .field
    = f.label :title
    = f.text_field :title, placeholder: 'z.B. Spender*innenurkunde'
  
  .field
    = f.label :category
    = f.text_field :category, placeholder: 'z.B. Ereignisse'
  
  .field
    = f.label :available
    .help
      Wie oft kann das Produkt bestellt werden? Wenn unbegrenzt, dann
      %strong nichts
      eintragen.
    
    = f.number_field :available
  
  .field
    = f.label :description
    .help Hier eine aussagekräftige Beschreibung des Produkts, die den Spender:innen Lust auf das Dankeschön machen soll.
    = f.text_area :description, rows: 5, placeholder: 'z.B. Urkunde auf handgeschöpftem Papier mit Unterschrift...'
  
  .field
    = f.label :delivery
    .help Freies Textfeld mit Details zur Lieferung.
    = f.text_field :delivery, placeholder: 'z.B. ab März 2022'
  
  .actions
    = cancel_action
    = f.submit
  

app/views/rewards/_preview.html.haml
%li.reward.collapsed
  - if reward.has_picture?
    = render 'general/picture_article', entity: reward
  
  .reward_infos
    .title= reward.title
    
    .amount= number_to_currency reward.price
    
    - if h_reward_editable?( reward )
      .action_buttons
        = link_to image_tag( 'sym/pencil_w100.svg' ), edit_reward_path( reward ), class: 'sym_button'
        = link_to image_tag( 'sym/bin_w100.svg' ), reward, method: :delete, class: 'sym_button danger', data: { confirm: "Willst du wirklich das Produkt '#{reward.title} löschen?\n\nDie Aktion kann nicht rückgängig gemacht werden." }
      
    
    .description= h_format reward.description
    
    .ordered
      - if reward.ordered > 0
        = reward.ordered
      - else
        noch keins
      
      bestellt
      - unless reward.available.blank?
        &mdash;
        = reward.available - reward.ordered
        verfügbar
        
      
    
    = render 'rewards/delivery_infos', reward: reward
  

app/views/rewards/_preview_for_funding.html.haml
%li.reward.collapsed
  - if reward.has_picture?
    = render 'general/picture_article', entity: reward
  
  .reward_infos
    .amount= number_to_currency reward.price
    
    .title= reward.title
    
    .description= h_format reward.description
    
    .delivery
      - unless reward.delivery.blank?
        Lieferung
        = reward.delivery
      - else
        keine Lieferinfos
      
    
    .action_buttons
      = link_to 'Auswählen', new_reward_donation_path( reward ), class: 'button'
      
      - if h_reward_editable?( reward )
        = link_to image_tag( 'sym/pencil_w100.svg' ), edit_reward_path( reward ), class: 'sym_button'
        = link_to image_tag( 'sym/bin_w100.svg' ), reward, method: :delete, class: 'sym_button danger', data: { confirm: "Willst du wirklich das Produkt '#{reward.title} löschen?\n\nDie Aktion kann nicht rückgängig gemacht werden." }
      
    
    .ordered
      - if reward.ordered > 0
        = reward.ordered
      - else
        noch keins
      
      - unless reward.available.blank?
        von
        = reward.available
      
      bestellt
    
  

app/views/rewards/edit.html.haml
- cancel_target = @reward.funding ? @reward.funding : rewards_path
- cancel_action = capture do
  = link_to 'Abbrechen', cancel_target, class: 'button secondary'

%h1 Produkt ändern

= render 'form', cancel_action: cancel_action

app/views/rewards/index.html.haml
- h_title 'Unsere Produkte'
- h_description( h_page_description_for 'rewards' )

%h1 Unsere Produkte
%p
  Hier erfährst du mehr über die Produkte, die
  %strong= h_orga_name
  anbietet

- if h_is_sales?
  %p
    = link_to 'Neues Produkt...', new_reward_path
  

%ul.rewards_list
  - @rewards.each do |reward|
    = render 'preview', reward: reward
  

app/views/rewards/new.html.haml
- cancel_target = @reward.funding ? @reward.funding : rewards_path
- cancel_action = capture do
  = link_to 'Abbrechen', cancel_target, class: 'button'


%h1 Neues Produkt
%p
  Hier kannst du ein neues Produkt
  - if @reward.funding
    für die Finanzierung
    %strong= @reward.funding.title
  erstellen.

= render 'form', cancel_action: cancel_action